source 'https://rubygems.org'

gem 'rails', '4.1.6'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'unicorn'
gem 'devise'
gem 'kaminari'
gem 'slim'
gem 'bootstrap-kaminari-views'
gem 'simple_form'
gem 'nested_form'
gem 'rails_12factor', group: :production
gem 'bootstrap-sass'
gem 'pry'
gem 'friendly_id'
gem 'cancan', git: "https://github.com/nukturnal/cancan.git"
gem 'bootstrap-kaminari-views'
gem 'redcarpet'
gem 'markitup-rails'